/* eslint-disable @typescript-eslint/no-var-requires */

const gitCommit = require('child_process')
  .execSync('git rev-parse HEAD')
  .toString()
  .trim()
  .substring(0, 10);
const gitBranch = require('child_process')
  .execSync('git rev-parse --abbrev-ref HEAD')
  .toString()
  .trim();
const buildDate = dateAsYYYYMMDDHHNNSS(new Date());
const appVersion = require('./package.json').version;

const fileContent = `// This file is automatically generated by build script. DO NOT MODIFY
export const BuildInfo = {
  revision: '${gitCommit}',
  branch: '${gitBranch}',
  buildDate: '${buildDate}',
  appVersion: '${appVersion}'
};
`;
console.log(fileContent);

require('fs').writeFile('./apps/oms/src/app/build-info.ts', fileContent, (err: Error) => {
  if (err) {
    console.error(err);
  }
});

// Helpers
function dateAsYYYYMMDDHHNNSS(date: Date): string {
  return (
    date.getFullYear() +
    '/' +
    leftPad(date.getMonth() + 1, 2) +
    '/' +
    leftPad(date.getDate(), 2) +
    ' ' +
    leftPad(date.getHours(), 2) +
    ':' +
    leftPad(date.getMinutes(), 2) +
    ':' +
    leftPad(date.getSeconds(), 2)
  );
}

function leftPad(val: number, resultLength = 2, leftPadChar = '0'): string {
  return (String(leftPadChar).repeat(resultLength) + String(val)).slice(String(val).length);
}
